name: "Build Status Action"
description: "Returns build result"

inputs:
 username:
  required:true
  description:"User Name"



outputs:
  result:
    description: "Build result"
    value: ${{ steps.set-status.outputs.result }} 

runs:
  using: "composite"

  steps:
    - name: Create Greeting
      run: echo "message=Hello ${{ inputs.username}}"" >> $GITHUB_OUTPUT 
      shell: bash