name: Java CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '17'

      
      - name: Run Greeting Action
        id: greet-action
        uses: ./.github/actions/java-build
        with:
         username:Chethiya 


      - name: Show Greeting
        run: echo "${{ steps.greet-action.outputs.message }}"